controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

kurse_show:
  path: /kurse/{id}
  controller: App\Controller\DetailsController::show
  defaults:
    {
      _controller: 'App\Controller\DetailsController::show',
      entityType: "kurse",
    }
  requirements:
    id: \d+

kunden_show:
  path: /kunden/{id}
  controller: App\Controller\DetailsController::show
  defaults:
    {
      _controller: 'App\Controller\DetailsController::show',
      entityType: "kunden",
    }
  requirements:
    id: \d+
